spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/med_reminder
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
server:
  port: 8085
logging:
  level:
    root: INFO
    com.medreminder: DEBUG
