spring.datasource.url=jdbc:postgresql://localhost:5432/med_reminder?ssl=false&trustServerCertificate=true
spring.datasource.username=medreminder
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.contexts=development
spring.liquibase.drop-first=false
spring.main.banner-mode=off
spring.main.web-application-type=none
logging.level.liquibase=DEBUG